name: Publish

on:
  push:
    branches: # Snapshots
      - main
    tags: ["**"] # Releases
  release:
    types: [published]

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@publish_gha_for_sbt_repo
    secrets: inherit
